from __future__ import annotations

from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import (
    QFrame, QHBoxLayout, QLabel, QLineEdit, QPushButton, QScrollArea,
    QVBoxLayout, QWidget,
)

from ..widgets import _MAX_REFRESH_LIMIT, _RefreshLimitValidator, _add_card_shadow


class _PenguinFeaturePage(QWidget):
    back_requested = Signal()

    def __init__(self, parent: QWidget | None = None) -> None:
        super().__init__(parent)
        self.setObjectName("penguinFeaturePage")
        outer = QVBoxLayout(self)
        outer.setContentsMargins(52, 28, 52, 42)
        outer.setSpacing(20)
        self.back_button = QPushButton("←  返回功能中心")
        self.back_button.setObjectName("penguinBackToModulesButton")
        self.back_button.setCursor(Qt.CursorShape.PointingHandCursor)
        self.back_button.clicked.connect(self.back_requested.emit)
        outer.addWidget(self.back_button, 0, Qt.AlignmentFlag.AlignLeft)
        heading = QLabel("红叶换企鹅")
        heading.setObjectName("pageHeading")
        outer.addWidget(heading)
        scroll = QScrollArea()
        scroll.setObjectName("featureScrollArea")
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        content = QWidget()
        content.setObjectName("featureContent")
        layout = QVBoxLayout(content)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(24)
        card = QFrame()
        card.setObjectName("settingsCard")
        settings = QVBoxLayout(card)
        settings.setContentsMargins(30, 26, 30, 30)
        settings.setSpacing(24)
        row = QHBoxLayout()
        label = QLabel("购买次数上限")
        label.setObjectName("settingLabel")
        self.limit_input = QLineEdit("0")
        self.limit_input.setObjectName("penguinPurchaseLimitInput")
        self.limit_input.setValidator(_RefreshLimitValidator(self.limit_input))
        self.limit_input.setMaxLength(len(str(_MAX_REFRESH_LIMIT)))
        self.limit_input.setInputMethodHints(Qt.InputMethodHint.ImhDigitsOnly)
        self.limit_input.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        self.limit_input.setFixedSize(260, 56)
        label.setBuddy(self.limit_input)
        row.addWidget(label)
        row.addStretch(1)
        row.addWidget(self.limit_input)
        settings.addLayout(row)
        cost_row = QHBoxLayout()
        cost_label = QLabel("预计消耗红叶")
        cost_label.setObjectName("settingLabel")
        self.leaf_cost_display = QLabel()
        self.leaf_cost_display.setObjectName("penguinLeafCostDisplay")
        self.leaf_cost_display.setAccessibleName("预计消耗红叶")
        self.leaf_cost_display.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.leaf_cost_display.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        self.leaf_cost_display.setFixedSize(260, 56)
        self.leaf_cost_display.setToolTip("按每次购买消耗 5100 红叶计算")
        cost_row.addWidget(cost_label)
        cost_row.addStretch(1)
        cost_row.addWidget(self.leaf_cost_display)
        settings.addLayout(cost_row)
        self.limit_input.textChanged.connect(self._update_leaf_cost)
        self._update_leaf_cost()
        self.start_button = QPushButton("启动脚本")
        self.start_button.setObjectName("penguinStartButton")
        self.start_button.setCursor(Qt.CursorShape.PointingHandCursor)
        self.start_button.setFixedHeight(68)
        settings.addWidget(self.start_button)
        _add_card_shadow(card)
        layout.addWidget(card)
        hint_card = QFrame()
        hint_card.setObjectName("shortcutCard")
        hint = QHBoxLayout(hint_card)
        hint.setContentsMargins(30, 24, 30, 26)
        key = QLabel("F5")
        key.setObjectName("keycap")
        key.setAlignment(Qt.AlignmentFlag.AlignCenter)
        key.setFixedSize(52, 44)
        hint.addWidget(key)
        hint.addWidget(QLabel("结束脚本"))
        hint.addStretch(1)
        _add_card_shadow(hint_card)
        layout.addWidget(hint_card)
        layout.addStretch(1)
        scroll.setWidget(content)
        outer.addWidget(scroll, 1)

    def purchase_limit(self) -> int | None:
        return int(self.limit_input.text()) if self.limit_input.hasAcceptableInput() else None

    def _update_leaf_cost(self) -> None:
        limit = self.purchase_limit()
        self.leaf_cost_display.setText(f"{limit * 5100:,}" if limit is not None else "—")
